######### Variáveis de ambiente
@token = "MzY._IpcLdMNytwk6p5PkAOe5-n9wCb405YQoD0q53RJhV3lcMxZ-T9_gRHqmPg6"

######### Cadastro de Mensagem
POST http://127.0.0.1:3333/messages HTTP/1.1
Content-Type: application/json
Authorization: Bearer MzY._IpcLdMNytwk6p5PkAOe5-n9wCb405YQoD0q53RJhV3lcMxZ-T9_gRHqmPg6

{
    "title": "Olá",
    "message": "Terceira mensagem do chat!"
}

######### Listar todos as Mensagens
GET http://127.0.0.1:3333/messages HTTP/1.1
Content-Type: application/json

######### Listar Mensagem específica
GET http://127.0.0.1:3333/messages/12 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MzY._IpcLdMNytwk6p5PkAOe5-n9wCb405YQoD0q53RJhV3lcMxZ-T9_gRHqmPg6

######### Alterar Mensagem
PUT http://127.0.0.1:3333/messages/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
{
    "title": "Olá",
    "message": "Mensagem do chat alterada!"
}

######### Apagar Mensagem
DELETE http://127.0.0.1:3333/messages/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
