######### Cadastro de Mensagem
POST http://127.0.0.1:3333/messages HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.PumXyNpu9QmizvQRjFVyQmH6nQXA-Lyh_YESHiupUXhExRgJG7ep3T4OnExz
{
    "title": "Olá",
    "message": "Segunda mensagem do chat!"
}

######### Listar todos as Mensagens
GET http://127.0.0.1:3333/messages HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.PumXyNpu9QmizvQRjFVyQmH6nQXA-Lyh_YESHiupUXhExRgJG7ep3T4OnExz

######### Listar Mensagem específica
GET http://127.0.0.1:3333/messages/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.PumXyNpu9QmizvQRjFVyQmH6nQXA-Lyh_YESHiupUXhExRgJG7ep3T4OnExz

######### Alterar Mensagem
PUT http://127.0.0.1:3333/messages/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.PumXyNpu9QmizvQRjFVyQmH6nQXA-Lyh_YESHiupUXhExRgJG7ep3T4OnExz
{
    "title": "Olá",
    "message": "Mensagem do chat alterada!"
}

######### Apagar Mensagem
DELETE http://127.0.0.1:3333/messages/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.PumXyNpu9QmizvQRjFVyQmH6nQXA-Lyh_YESHiupUXhExRgJG7ep3T4OnExz
