######### Cadastro Tópico
POST http://127.0.0.1:3333/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer MzY._IpcLdMNytwk6p5PkAOe5-n9wCb405YQoD0q53RJhV3lcMxZ-T9_gRHqmPg6

{
    "name": "Web1"
}

######### Listar todos os Tópico
GET http://127.0.0.1:3333/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer MzY._IpcLdMNytwk6p5PkAOe5-n9wCb405YQoD0q53RJhV3lcMxZ-T9_gRHqmPg6


######### Listar Tópico específico
GET http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MzY._IpcLdMNytwk6p5PkAOe5-n9wCb405YQoD0q53RJhV3lcMxZ-T9_gRHqmPg6

######### Alterar Tópico
PUT http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MzY._IpcLdMNytwk6p5PkAOe5-n9wCb405YQoD0q53RJhV3lcMxZ-T9_gRHqmPg6

{
    "name": "Web II"
}

######### Apagar Tópico
DELETE http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MzY._IpcLdMNytwk6p5PkAOe5-n9wCb405YQoD0q53RJhV3lcMxZ-T9_gRHqmPg6

