######### Cadastro Tópico
POST http://127.0.0.1:3333/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mw.Vd7n2tKgYkloYES9KYVUicmv9DsH_tmRNMXIdgHDyVb_YTCNzDSi3GokN4va

{
    "name": "METALLICA"
}

######### Listar todos os Tópico
GET http://127.0.0.1:3333/topics HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mw.Vd7n2tKgYkloYES9KYVUicmv9DsH_tmRNMXIdgHDyVb_YTCNzDSi3GokN4va


######### Listar Tópico específico
GET http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mw.Vd7n2tKgYkloYES9KYVUicmv9DsH_tmRNMXIdgHDyVb_YTCNzDSi3GokN4va

######### Alterar Tópico
PUT http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mw.Vd7n2tKgYkloYES9KYVUicmv9DsH_tmRNMXIdgHDyVb_YTCNzDSi3GokN4va

{
    "name": "MEGADETH"
}

######### Apagar Tópico
DELETE http://127.0.0.1:3333/topics/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer Mw.Vd7n2tKgYkloYES9KYVUicmv9DsH_tmRNMXIdgHDyVb_YTCNzDSi3GokN4va

